spring:
  application:
    name: adminservice
  cloud:
      config:
        profile: prod
  security:
    user:
      name: adminProd
      password: adminProdPassword123
eureka:
  instance:
    # Fuerza a que se registren por IP, que es lo más estable en redes de Docker
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaProdUser:eurekaProdPassword123@eurekaserver:8761/eureka/
server:
  forward-headers-strategy: framework
  port: "8084"