spring:
  application:
    name: gateway
  security:
      oauth2:
        client:
          registration:
            keycloak-hospital:
              client-id: hospital-gateway
              client-secret: tu_secreto_de_keycloak # Generado en Keycloak
              scope: openid, profile, email
              authorization-grant-type: authorization_code
              redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          provider:
            keycloak-hospital:
              issuer-uri: http://keycloak:8080/realms/hospital-realm
              authorization-uri: http://localhost:8180/realms/hospital-realm/protocol/openid-connect/auth

  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: modulo-pacientes
          uri: lb://MODULO-PACIENTES
          predicates:
           - Path=/api/pacientes/**
# Borra "/api/pacientes" de la URL antes de enviar la petición al microservicio
          filters:
          - StripPrefix=2 
          - TokenRelay
        - id: modulo-atenciones
          uri: lb://MODULO-ATENCIONES
          predicates:
           - Path=/api/atenciones/**
# Borra "/api/atenciones" de la URL antes de enviar la petición al microservicio
          filters:
          - StripPrefix=2
          - TokenRelay
    loadbalancer:
      ribbon:
        enabled: false
  boot:
    admin:
      client:
        url: http://adminservice:8084
        username: adminProd
        password: adminProdPassword123
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    prefer-ip-address: true
  client:
    service-url:
        defaultZone: http://eurekaProdUser:eurekaProdPassword123@eurekaserver:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
# Ordena los servicios alfabéticamente en el menú desplegable
    operationsSorter: alpha
    tagsSorter: alpha
# Habilita la detección automática basada en las rutas de arriba
    use-root-path: true
    urls:
     - name: modulo-pacientes
       url: /api/pacientes/v3/api-docs
     - name: modulo-atenciones
       url: /api/atenciones/v3/api-docs
server:
  port: "8080"