spring:
  application:
    name: modulo-atenciones
  cloud:
      config:
        profile: prod
        uri: http://configUserProd:configPasswordProd123@configserver:8888
  h2:
    console:
      enabled: true
  datasource:
      url: jdbc:mysql://db:3306/hospitaldb
      username: admin
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

  boot:
      admin:
        client:
          url: http://admin-service:8084
          name: adminProd
          password: adminProdPassword123

  security:
    oauth2:
      resource-server:
        jwt:
          # Firma exacta esperada del emisor
          issuer-uri: http://localhost:8180/realms/hospital-realm
          # Descarga de llaves públicas mediante la red interna de Docker
          jwk-set-uri: http://keycloak:8080/realms/hospital-realm/protocol/openid-connect/certs

management:
  endpoints:
     web:
      exposure:
          include: "*"
eureka:
  instance:
    # Fuerza a que se registren por IP, que es lo más estable en redes de Docker
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
        defaultZone: http://eurekaProdUser:eurekaProdPassword123@eurekaserver:8761/eureka/
server:
  port: '8081'
  forward-headers-strategy: framework