spring:
  application:
    name: modulo-pacientes
  cloud:
    config:
      profile: dev
      uri: http://configUser:configPassword123@localhost:8888
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  devtools:
      restart:
        enabled: 'false'
  boot:
    admin:
      client:
        url: http://localhost:8084
        username: adminUser
        password: adminPassword123
  security:
    oauth2:
      resource-server:
        jwt:
          # URL ficticia obligatoria para evitar que falle la auto-configuración de Spring al iniciar
          issuer-uri: http://localhost:9999/mock-realm
  management:
      endpoints:
        web:
          exposure:
            include: "*"

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
        defaultZone: http://eurekaUser:eurekaPassword123@localhost:8761/eureka/
    enabled: true

server:
  forward-headers-strategy: framework
  port: "8082"
 